sudo: required
serivces:
  - docker

before_install:
  - docker build -t ankurrathore/react-test -f ./clients/Dockerfile.dev ./clients

script:
  - docker run -e CI=true ankurrathore/react-test npm test -- --coverage

after_success:
  - docker build -t ankurrathore/multi-clients ./clients
  - docker build -t ankurrathore/multi-nginx ./nginx
  - docker build -t ankurrathore/multi-server ./server
  - docker build -t ankurrathore/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing the images to Docker Hub
  - docker push ankurrathore/multi-clients
  - docker push ankurrathore/multi-nginx
  - docker push ankurrathore/multi-server
  - docker push ankurrathore/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: " MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-071239014041"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"